### PR TITLE
 `deploy-tool`: don't generate packet encryption key twice #756 

### LINKED ISSUE #756: `deploy-tool`: don't generate packet encryption key twice
#572 introduced a regression into `deploy-tool`: when generating keys and manifests for a newly deployed locality, `deploy-tool` generates the packet encryption key (which is shared across both ingestors in a locality, as opposed to the batch signing key which is unique for each (ingestor, locality) pair) twice, and updates the Kubernetes secret twice. As a consequence, whichever manifest gets generated first will contain a packet encryption key CSR that does not correspond to the private key used by either ingestor's `intake-batch` or `aggregate` worker deployment. 

The MITRE component that fetches packet encryption key CSRs happens to consult the locality's `g-enpa` manifest, meaning this bug is benign if that manifest is generated last (which is what happened in `us-dc`), but if the `apple` one gets generated last, then clients will be configured with the wrong key (which is what happened in `us-la`). Go iterates over maps in a random order, which is why this bug can sometimes be benign.

### PR DESCRIPTION
**Pull request by tgeoghegan**
In an effort to make this a bit easier to review, commit 171bbdd contains just the bugfix, and then 3d283eb has some refactoring to make this testable.

Resolves #756

### CODE REVIEW

File: deploy-tool/main.go [hunk 1]
```diff
@@ -132,26 +132,85 @@ func generateAndDeployKeyPair(
 	return p256Key, nil
 }
 
-func manifestExists(fqdn, dsp string) bool {
-	// Remove the locality name from the FQDN
-	path := fmt.Sprintf("https://%s/%s-manifest.json", fqdn, dsp)
+// globalManifestExists checks if a global data share processor manifest exists
+// relative to the manifest base URL provided, returning (true, nil) if so,
+// (false, nil) if not, and (false, error) if it could be determined
+func globalManifestExists(manifestBaseURL string) (bool, error) {
```
Comment (jcjones) [inline deploy-tool/main.go:138]: Optimally this would be a thin wrapper for a method `fetchManifest` that could be called here and down in Fetcher so the status code and Sprintf-work could be consolidated by returning the response object in some way or other, but basically all this is a bit miserable so I think I agree with duplicating the code for this poor tool.

File: deploy-tool/main.go [hunk 2]
```diff
@@ -235,27 +289,22 @@ func createManifest(
...
-	certificatesByNamespace := manifest.PacketEncryptionKeyCSRs{}
-	newCertificates := manifest.PacketEncryptionKeyCSRs{}
-	for name, packetEncryptionCertificate := range manifestWrapper.SpecificManifest.PacketEncryptionKeyCSRs {
-		if packetEncryptionCertificate.CertificateSigningRequest != "" {
-			newCertificates[name] = packetEncryptionCertificate
-			continue
+	for name, packetEncryptionCertificateSigningRequest := range manifestWrapper.SpecificManifest.PacketEncryptionKeyCSRs {
+		if packetEncryptionCertificateSigningRequest.CertificateSigningRequest != "" {
+			// We never create CSRs in Terraform, so this should never happen
+			return fmt.Errorf("unexpected packet encryption key CSR in Terraform output")
```
Comment (jcjones) [inline deploy-tool/main.go:298]: might be worthwhile to indicate `name` in this Errorf since it is already formatted.
```suggestion
			return fmt.Errorf("unexpected packet encryption key CSR in Terraform output for name %s", name)
```

File: deploy-tool/main.go [hunk 3]
```diff
@@ -207,25 +266,20 @@ func createBatchSigningPublicKey(
...
-	k8sSecretsClient := k8sClient.CoreV1().Secrets(manifestWrapper.KubernetesNamespace)
+	k8sSecretsClient := k8sSecretsClientGetter.Secrets(manifestWrapper.KubernetesNamespace)
 
-	newBatchSigningPublicKeys := manifest.BatchSigningPublicKeys{}
 	for name, batchSigningPublicKey := range manifestWrapper.SpecificManifest.BatchSigningPublicKeys {
 		if batchSigningPublicKey.PublicKey != "" {
-			newBatchSigningPublicKeys[name] = batchSigningPublicKey
-			continue
+			// We never create keys in Terraform, so this should never happen
+			return fmt.Errorf("unexpected batch signing key in Terraform output")
```
Comment (jcjones) [inline deploy-tool/main.go:280]: might be worthwhile to indicate `name` in this Errorf since it is already formatted.
```suggestion
			return fmt.Errorf("unexpected batch signing key in Terraform output for name %s", name)
```

File: deploy-tool/main.go [hunk 4]
```diff
@@ -338,6 +387,61 @@ func backupKeys(
...
+			return err
+		}
+
+		if manifest == nil {
+			continue
+		}
+
+		existingManifests[dataShareProcessorName] = struct{}{}
+
+		for keyName, certificateSigningRequest := range manifest.PacketEncryptionKeyCSRs {
```
Comment (jcjones) [inline deploy-tool/main.go:415]: I understand the preconditions expected here, but ISTM we should verify that if `packetEncryptionKeyCSRs[keyName]` is not empty here, that it has the same CSR rather than clobbering it indiscriminately. 

This obviously can't happen when there are only two processors in the first place, but it'd be a painful bug if there were >2. Maybe it could just confirm that the key is empty for right now, and when this gets modified to handle additional processors as it might well be, it'll fail at that point and we can address it properly then.

**Review by jcjones — DISMISSED** [review]

File: deploy-tool/main.go (hunk 1 above)
Comment (tgeoghegan) [reply deploy-tool/main.go:138]: I agree. Where I got hung up here is that in one case, all I care about is whether it exists, and in the other, I need the actual manifest. In any case this gets refactored away in #763 which is also why I was OK with letting this be ugly for that brief time between when this PR is merged and when that one lands.

File: deploy-tool/main.go [hunk 5]
```diff
@@ -132,26 +132,85 @@ func generateAndDeployKeyPair(
...
+func globalManifestExists(manifestBaseURL string) (bool, error) {
+	url := fmt.Sprintf("https://%s/global-manifest.json", manifestBaseURL)
+
+	resp, err := http.Get(url)
+	if err != nil {
+		return false, fmt.Errorf("error fetching manifest %s: %w", url, err)
+	}
+	defer resp.Body.Close()
+
+	if resp.StatusCode == 403 || resp.StatusCode == 404 {
```
Comment (aaomidi) [inline deploy-tool/main.go:147]: nit: We could probably abstract away the http call and error handling into its own function. I believe we're doing these generic if checks in multiple places now.

**Review by aaomidi — APPROVED** [review]

File: deploy-tool/main.go (hunk 5 above)
Comment (tgeoghegan) [reply deploy-tool/main.go:147]: J.C. made a similar observation, and my answer is that all of this gets refactored away in #763, which is context I should have provided in this PR.
